# Generated by Django 3.2.9 on 2021-11-08 18:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_formfield_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission_section_title',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Describe your mission'),
        ),
    ]
