# Generated by Django 3.2.9 on 2021-11-09 10:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_mission_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mission_section_title',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Title of your mission title'),
        ),
    ]
