# Generated by Django 3.2.9 on 2021-11-09 10:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='catalog.paintingdetailpage'),
        ),
    ]
